spring:
  application:
    name: cinema
  datasource:
    url: jdbc:postgresql://localhost:5433/BookingCinema
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    clean-disabled: true
    table: flyway_schema_history
    placeholder-replacement: true
    placeholders:
      senha_admin_hash: ${ADMIN_PASSWORD_HASH}
  jpa:
    hibernate:
      ddl-auto: none

jwt:
  secret: ${JWT_SECRET}
  expiration: PT1H

api:
  stripe:
    key: ${STRIPE_SECRET_KEY}

app:
  webhooks:
    stripe:
      secret-key: ${STRIPE_WEBHOOK_SECRET}

logging:
  level:
    org.springframework.security: DEBUG